// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nativeBridge.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PJ.Native.Proto {

  /// <summary>Holder for reflection information generated from nativeBridge.proto</summary>
  public static partial class NativeBridgeReflection {

    #region Descriptor
    /// <summary>File descriptor for nativeBridge.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NativeBridgeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJuYXRpdmVCcmlkZ2UucHJvdG8iNQoHTWVzc2FnZRILCgNrZXkYASABKAkS",
            "HQoJY29udGFpbmVyGAIgASgLMgouQ29udGFpbmVyIssECglDb250YWluZXIS",
            "KAoHYm9vbE1hcBgBIAMoCzIXLkNvbnRhaW5lci5Cb29sTWFwRW50cnkSJgoG",
            "aW50TWFwGAIgAygLMhYuQ29udGFpbmVyLkludE1hcEVudHJ5EioKCGZsb2F0",
            "TWFwGAMgAygLMhguQ29udGFpbmVyLkZsb2F0TWFwRW50cnkSLAoJc3RyaW5n",
            "TWFwGAQgAygLMhkuQ29udGFpbmVyLlN0cmluZ01hcEVudHJ5EioKCGJ5dGVz",
            "TWFwGAUgAygLMhguQ29udGFpbmVyLkJ5dGVzTWFwRW50cnkSMgoMY29udGFp",
            "bmVyTWFwGAYgAygLMhwuQ29udGFpbmVyLkNvbnRhaW5lck1hcEVudHJ5Gi4K",
            "DEJvb2xNYXBFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAg6AjgB",
            "Gi0KC0ludE1hcEVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoBToC",
            "OAEaLwoNRmxvYXRNYXBFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiAB",
            "KAI6AjgBGjAKDlN0cmluZ01hcEVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1",
            "ZRgCIAEoCToCOAEaLwoNQnl0ZXNNYXBFbnRyeRILCgNrZXkYASABKAkSDQoF",
            "dmFsdWUYAiABKAw6AjgBGj8KEUNvbnRhaW5lck1hcEVudHJ5EgsKA2tleRgB",
            "IAEoCRIZCgV2YWx1ZRgCIAEoCzIKLkNvbnRhaW5lcjoCOAFCEqoCD1BKLk5h",
            "dGl2ZS5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PJ.Native.Proto.Message), global::PJ.Native.Proto.Message.Parser, new[]{ "Key", "Container" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PJ.Native.Proto.Container), global::PJ.Native.Proto.Container.Parser, new[]{ "BoolMap", "IntMap", "FloatMap", "StringMap", "BytesMap", "ContainerMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Message : pb::IMessage<Message>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PJ.Native.Proto.NativeBridgeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message(Message other) : this() {
      key_ = other.key_;
      container_ = other.container_ != null ? other.container_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "container" field.</summary>
    public const int ContainerFieldNumber = 2;
    private global::PJ.Native.Proto.Container container_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PJ.Native.Proto.Container Container {
      get { return container_; }
      set {
        container_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (!object.Equals(Container, other.Container)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (container_ != null) hash ^= Container.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (container_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Container);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (container_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Container);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (container_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Container);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.container_ != null) {
        if (container_ == null) {
          Container = new global::PJ.Native.Proto.Container();
        }
        Container.MergeFrom(other.Container);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            if (container_ == null) {
              Container = new global::PJ.Native.Proto.Container();
            }
            input.ReadMessage(Container);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            if (container_ == null) {
              Container = new global::PJ.Native.Proto.Container();
            }
            input.ReadMessage(Container);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Container : pb::IMessage<Container>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Container> _parser = new pb::MessageParser<Container>(() => new Container());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Container> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PJ.Native.Proto.NativeBridgeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Container() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Container(Container other) : this() {
      boolMap_ = other.boolMap_.Clone();
      intMap_ = other.intMap_.Clone();
      floatMap_ = other.floatMap_.Clone();
      stringMap_ = other.stringMap_.Clone();
      bytesMap_ = other.bytesMap_.Clone();
      containerMap_ = other.containerMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Container Clone() {
      return new Container(this);
    }

    /// <summary>Field number for the "boolMap" field.</summary>
    public const int BoolMapFieldNumber = 1;
    private static readonly pbc::MapField<string, bool>.Codec _map_boolMap_codec
        = new pbc::MapField<string, bool>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForBool(16, false), 10);
    private readonly pbc::MapField<string, bool> boolMap_ = new pbc::MapField<string, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, bool> BoolMap {
      get { return boolMap_; }
    }

    /// <summary>Field number for the "intMap" field.</summary>
    public const int IntMapFieldNumber = 2;
    private static readonly pbc::MapField<string, int>.Codec _map_intMap_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 18);
    private readonly pbc::MapField<string, int> intMap_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> IntMap {
      get { return intMap_; }
    }

    /// <summary>Field number for the "floatMap" field.</summary>
    public const int FloatMapFieldNumber = 3;
    private static readonly pbc::MapField<string, float>.Codec _map_floatMap_codec
        = new pbc::MapField<string, float>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForFloat(21, 0F), 26);
    private readonly pbc::MapField<string, float> floatMap_ = new pbc::MapField<string, float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, float> FloatMap {
      get { return floatMap_; }
    }

    /// <summary>Field number for the "stringMap" field.</summary>
    public const int StringMapFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_stringMap_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<string, string> stringMap_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> StringMap {
      get { return stringMap_; }
    }

    /// <summary>Field number for the "bytesMap" field.</summary>
    public const int BytesMapFieldNumber = 5;
    private static readonly pbc::MapField<string, pb::ByteString>.Codec _map_bytesMap_codec
        = new pbc::MapField<string, pb::ByteString>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForBytes(18, pb::ByteString.Empty), 42);
    private readonly pbc::MapField<string, pb::ByteString> bytesMap_ = new pbc::MapField<string, pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, pb::ByteString> BytesMap {
      get { return bytesMap_; }
    }

    /// <summary>Field number for the "containerMap" field.</summary>
    public const int ContainerMapFieldNumber = 6;
    private static readonly pbc::MapField<string, global::PJ.Native.Proto.Container>.Codec _map_containerMap_codec
        = new pbc::MapField<string, global::PJ.Native.Proto.Container>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::PJ.Native.Proto.Container.Parser), 50);
    private readonly pbc::MapField<string, global::PJ.Native.Proto.Container> containerMap_ = new pbc::MapField<string, global::PJ.Native.Proto.Container>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::PJ.Native.Proto.Container> ContainerMap {
      get { return containerMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Container);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Container other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!BoolMap.Equals(other.BoolMap)) return false;
      if (!IntMap.Equals(other.IntMap)) return false;
      if (!FloatMap.Equals(other.FloatMap)) return false;
      if (!StringMap.Equals(other.StringMap)) return false;
      if (!BytesMap.Equals(other.BytesMap)) return false;
      if (!ContainerMap.Equals(other.ContainerMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= BoolMap.GetHashCode();
      hash ^= IntMap.GetHashCode();
      hash ^= FloatMap.GetHashCode();
      hash ^= StringMap.GetHashCode();
      hash ^= BytesMap.GetHashCode();
      hash ^= ContainerMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      boolMap_.WriteTo(output, _map_boolMap_codec);
      intMap_.WriteTo(output, _map_intMap_codec);
      floatMap_.WriteTo(output, _map_floatMap_codec);
      stringMap_.WriteTo(output, _map_stringMap_codec);
      bytesMap_.WriteTo(output, _map_bytesMap_codec);
      containerMap_.WriteTo(output, _map_containerMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      boolMap_.WriteTo(ref output, _map_boolMap_codec);
      intMap_.WriteTo(ref output, _map_intMap_codec);
      floatMap_.WriteTo(ref output, _map_floatMap_codec);
      stringMap_.WriteTo(ref output, _map_stringMap_codec);
      bytesMap_.WriteTo(ref output, _map_bytesMap_codec);
      containerMap_.WriteTo(ref output, _map_containerMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += boolMap_.CalculateSize(_map_boolMap_codec);
      size += intMap_.CalculateSize(_map_intMap_codec);
      size += floatMap_.CalculateSize(_map_floatMap_codec);
      size += stringMap_.CalculateSize(_map_stringMap_codec);
      size += bytesMap_.CalculateSize(_map_bytesMap_codec);
      size += containerMap_.CalculateSize(_map_containerMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Container other) {
      if (other == null) {
        return;
      }
      boolMap_.MergeFrom(other.boolMap_);
      intMap_.MergeFrom(other.intMap_);
      floatMap_.MergeFrom(other.floatMap_);
      stringMap_.MergeFrom(other.stringMap_);
      bytesMap_.MergeFrom(other.bytesMap_);
      containerMap_.MergeFrom(other.containerMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            boolMap_.AddEntriesFrom(input, _map_boolMap_codec);
            break;
          }
          case 18: {
            intMap_.AddEntriesFrom(input, _map_intMap_codec);
            break;
          }
          case 26: {
            floatMap_.AddEntriesFrom(input, _map_floatMap_codec);
            break;
          }
          case 34: {
            stringMap_.AddEntriesFrom(input, _map_stringMap_codec);
            break;
          }
          case 42: {
            bytesMap_.AddEntriesFrom(input, _map_bytesMap_codec);
            break;
          }
          case 50: {
            containerMap_.AddEntriesFrom(input, _map_containerMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            boolMap_.AddEntriesFrom(ref input, _map_boolMap_codec);
            break;
          }
          case 18: {
            intMap_.AddEntriesFrom(ref input, _map_intMap_codec);
            break;
          }
          case 26: {
            floatMap_.AddEntriesFrom(ref input, _map_floatMap_codec);
            break;
          }
          case 34: {
            stringMap_.AddEntriesFrom(ref input, _map_stringMap_codec);
            break;
          }
          case 42: {
            bytesMap_.AddEntriesFrom(ref input, _map_bytesMap_codec);
            break;
          }
          case 50: {
            containerMap_.AddEntriesFrom(ref input, _map_containerMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
